import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx, { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { Analytics } from '@vercel/analytics/react';
import SiteHeader from "./widgets/header";
import { Footer } from "antd/es/layout/layout";
import { SiteFooter } from "./widgets/Footer";
import Contactus from "./widgets/ContactUs";
import { FloatingNav } from "@/components/ui/floating-navbar";

 
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const navItems = [

    {
      name: "Solution",
      link: "/solutions",
      productCategory: {
        "By Technology": [
          {

            products: [
              {
                title: "AI",
                href: "https://example.com/product-d",
                src: "https://example.com/product-d.webp",
                description: "NUEBGIUEBBVFHE FKUV FUE FHWFV BVWUBWDYUBHDBWUYDB VWDJHBWVDLJHWBDYU WBDLUYdbWLHj"
              }
              ,
              {
                title: "ERP",
                href: "https://example.com/product-d",
                src: "https://example.com/product-d.webp",
                description: "Description for Product D"
              }
              ,
              {
                title: "CRM",
                href: "https://example.com/product-d",
                src: "https://example.com/product-d.webp",
                description: "Description for Product D"
              }
              ,
              {
                title: "ZohO",
                href: "https://example.com/product-d",
                src: "https://example.com/product-d.webp",
                description: "Description for Product D"
              }
              ,
              {
                title: "Odoo",
                href: "https://example.com/product-d",
                src: "https://example.com/product-d.webp",
                description: "Description for Product D"
              }
              ,
            ]
          }

        ],
        "By Industry": [
          {
            products: [
              {
                title: "ERP For Pump Manufacturing",
                href: "/solutions/PumpManufacturing",
                src: "https://example.com/product-a.webp",
                description: "Description for Product A"
              },
              {
                title: "ERP For Engineering Manufacturing",
                href: "/solutions/EngineeringManufacturing",
                src: "https://example.com/product-b.webp",
                description: "Description for Product B"
              }
              ,
              {
                title: "ERP For Construction and Contracting Industry",
                href: "https://example.com/product-b",
                src: "https://example.com/product-b.webp",
                description: "Description for Product B"
              }
              ,
              {
                title: "ERP For Trading and Distribution",
                href: "https://example.com/product-b",
                src: "https://example.com/product-b.webp",
                description: "Description for Product B"
              }
              ,
              {
                title: "ERP For Education Domain",
                href: "https://example.com/product-b",
                src: "https://example.com/product-b.webp",
                description: "Description for Product B"
              }
            ]
          },
        ],

        "By Current Software": [
          {

            products: [
              {
                title: "MyTime",
                href: "https://example.com/product-e",
                src: "https://example.com/product-e.webp",
                description: "Description for Product E"
              }
              ,
              {
                title: "iStock",
                href: "https://example.com/product-e",
                src: "https://example.com/product-e.webp",
                description: "Description for Product E"
              }
              ,
              {
                title: "iERP",
                href: "https://example.com/product-e",
                src: "https://example.com/product-e.webp",
                description: "Description for Product E"
              }
              ,
              {
                title: "iAttendance",
                href: "https://example.com/product-e",
                src: "https://example.com/product-e.webp",
                description: "Description for Product E"
              }
              ,
              {
                title: "iAccount",
                href: "https://example.com/product-e",
                src: "https://example.com/product-e.webp",
                description: "Description for Product E"
              }
              ,
            ]
          }

        ]
      }
    },
    {
      name: "Industry We Served",
      link: "/",
      nestedSelection: [
        {
          name: "Industryyy",
          link: "/HI"
        }
      ]
    },
    {
      name: "Services",
      link: "/",
      nestedSelection: [
        {
          name: "HI",
          link: "/HI"
        }
      ]
    },
    {
      name: "Company",
      link: "/",
      nestedSelection: [
        {
          name: "HI",
          link: "/HI"
        }
      ]
    },
    {
      name: "Support",
      link: "/",
      nestedSelection: [
        {
          name: "HI",
          link: "/HI"
        }
      ]
    }
  ];

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>

      <body>
        <div className="relative w-full pt-10">
          <FloatingNav navItems={navItems} />
          {/* <ThemeToggleButton /> */}
          <div className={`${inter.variable} relative w-full --font-inter`}>{children}</div>
        </div>

        <Analytics />
        <div>

          <Contactus />
        </div>

        <div className="pt-20 mt-20">
          <SiteFooter />

        </div>
      </body>
    </html>
  );
}
// const Content = () => {
//   return (
//     <div className="grid grid-cols-1 h-[40rem] w-full bg-white dark:bg-black relative border border-neutral-200 dark:border-white/[0.2] rounded-md">
//       <p className="dark:text-white text-neutral-600 text-center text-4xl mt-40 font-bold">
//         Scroll back up to reveal Navbar
//       </p>
//       <div className="inset-0 absolute bg-grid-black/[0.1] dark:bg-grid-white/[0.2]" />
//     </div>
//   );
// };