import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx, { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { Analytics } from '@vercel/analytics/react';
import SiteHeader from "./widgets/header";
import { Footer } from "antd/es/layout/layout";
import { SiteFooter } from "./widgets/Footer";
import Contactus from "./widgets/ContactUs";
const inter = Inter({ subsets: ["latin"] });
// import '@mantine/core/styles.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      <body>
      <div className="pt-5">
      <SiteHeader/>
      </div>

      {children}
        <Analytics />
        <div>
            <Contactus/>
          </div>
       
        <div>
 <SiteFooter/>
            
          </div>
        </body>
    </html>
  );
}
