import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx, { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { Analytics } from '@vercel/analytics/react';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// export function cn(...inputs: ClassValue[]) {
//   return twMerge(clsx(...inputs));
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <Analytics /></body>
    </html>
  );
}
